name: pre-release
on:
  pull_request:
    paths:
      - '**.yml'
      - 'src/**'
      - 'config/**'
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install the vsce npm package
        run: |
          npm install
          npm install -g vsce
      - name: Run headless test
        uses: coactions/setup-xvfb@v1
        if: runner.os == 'Linux'
        with:
          run: xvfb-run -a npm test
      - name: Run test
        run: npm test
        if: runner.os != 'Linux'
      - name: Set Git identity
        run: |
          git config user.email "nickyinluo@tencent.com"
          git config user.name "nickyinluo"
      - name: Package extension
        if: success()
        run: npm run package.patch
        env:
          VSCE_PAT: ${{ secrets.VS_MARKETPLACE_TOKEN }}
      - name: Get Current Version
        id: vscode-ext-pkg-ver
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: Upload Package as pre-publish
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.vscode-ext-pkg-ver.outputs.current-version}}
          prerelease: true
          title: "v${{ steps.vscode-ext-pkg-ver.outputs.current-version}}"
          files: |
            vscode-tencentcloud-terraform-*.vsix
