name: pre-release
on:
    pull_request:
        types:
            - closed
    push:
        tags:
            - "v*"

jobs:
    pre-release:
        if: ${{ github.event.pull_request.labels.name == 'pre-release' }}
        permissions:
            contents: write
            pull-requests: write
        runs-on: ubuntu-latest
        environment: TOKEN_VSCODE
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
            - run: npm ci

            - name: Set Git identity
              run: |
                  git config user.email "nickyinluo@tencent.com"
                  git config user.name "nickyinluo"

            - name: Package extension
              if: success()
              run: |
                  npm run package.current
              env:
                  VSCE_PAT: ${{ secrets.VS_MARKETPLACE_TOKEN }}

            - name: Get Current Version
              id: vscode-ext-pkg-ver
              uses: martinbeentjes/npm-get-version-action@v1.3.1

            - name: Pre-release to Github
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: ${{ steps.vscode-ext-pkg-ver.outputs.current-version}}
                  prerelease: true
                  title: "v${{ steps.vscode-ext-pkg-ver.outputs.current-version}}-beta"
                  files: |
                      vscode-tencentcloud-terraform-*.vsix
