name: pre-release
on:
    pull_request:
        types:
            - closed
    push:
        tags:
            - "v*"

jobs:
    pre-release:
        permissions:
            contents: write
            pull-requests: write
        runs-on: ubuntu-latest
        environment: TOKEN_VSCODE
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
            - run: npm ci

            - name: Set tags from commit tag
              if: startsWith(github.ref, 'refs/tags/') || startsWith(github.event.push.ref, 'refs/tags/')
              run: |
                    NEW_TAG=${GITHUB_REF#refs/tags/}
                    echo "new tag[$NEW_TAG] from commit tag will be set"
                    echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

            - name: Get Current Version
              id: vscode-ext-pkg-ver
              uses: martinbeentjes/npm-get-version-action@v1.3.1

            - name: Set tags from label
              if: startsWith(github.ref, 'refs/heads/') || !startsWith(github.event.push.ref, 'refs/heads/')
              run: ｜
                echo "NEW_TAG=${{ steps.vscode-ext-pkg-ver.outputs.current-version}}" >> $GITHUB_ENV
                echo "new tag [$NEW_TAG] from label will be set"

            - name: Set Git identity
              run: |
                  git config user.email "nickyinluo@tencent.com"
                  git config user.name "nickyinluo"

            - name: Package extension
              if: success()
              run: |
                  npm run package.current
              env:
                  VSCE_PAT: ${{ secrets.VS_MARKETPLACE_TOKEN }}

            - name: Pre-release to Github
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: $NEW_TAG
                  prerelease: true
                  title: "v$NEW_TAG-beta"
                  files: |
                      vscode-tencentcloud-terraform-*.vsix
