name: release
on:
    release:
        types:
            - released

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Publish to vs marketplace 1
              if: success() && startsWith(github.ref, 'refs/tags/')
              run: npm run release.current
              env:
                  VSCE_PAT: ${{ secrets.VS_MARKETPLACE_TOKEN }}
